INSERT INTO PRODUCTO (ID, NOMBRE, PRECIO, UNIDADES_EN_STOCK, OBSERVACION, ESTA_EN_CESTA)
VALUES (NEXTVAL('hibernate_sequence'), 'Platanos',3.0, 100, 'Maduros', false);

INSERT INTO PRODUCTO (ID, NOMBRE, PRECIO, UNIDADES_EN_STOCK, OBSERVACION, ESTA_EN_CESTA)
VALUES (NEXTVAL('hibernate_sequence'), 'Fresas',4.0, 100, 'Verdes', false);